### ISSUE TITLE
Need some help? 

### ISSUE THREAD

**Issue by brockelmore** [xn3cr0nx/bitgodine#1]
Saw you have an interest in a go-based bitcoin parser. I was thinking of converting Blocksci into Go because the C++ is too unstable and cumbersome. You have some great work here already, want to some help?

**Comment by xn3cr0nx** [comment]
Hi, I'm working on this open source tools for my master's degree thesis. It is a more advanced implementation of a previous 2013 work https://github.com/mikispag/bitiodine, but this time using existing btcsuite libraries and improving scalability and functionalities. Other previous jobs used exactly Blocksci, but it is unstable on different release. So I'm implementing a new one andvanced go version. It is open source so, every help is welcome! I'm in initial phase as you saw and I'm following previous implementation, and then implements new features from Blocksci (currently parsing of .dat files).

**Comment by brockelmore** [comment]
I am mainly interested in address clustering and a better approximation of transaction volume. Mainly I want dynamic reclustering of addresses and live analysis capabilities (which means handling temporary forks from simultaneous mined blocks). I will look thru everything you have thus far and see what I can do to help
